import os
import logging
import traceback
from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
from dotenv import load_dotenv

import db
import engine

load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

app = Flask(__name__, static_folder=".", static_url_path="")
CORS(app, resources={r"/api/*": {"origins": "*"}})

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "").strip()
MAX_AI_REQUESTS_PER_DAY = int(os.environ.get("MAX_AI_REQUESTS_PER_DAY", "50"))

SYSTEM_PROMPT = """You are the diagnostic assistant for the AI-Powered Chatbot for Medical Diagnosis, a system designed to help users understand their symptoms before they see a physician.

Your responsibilities:
1. Listen carefully to reported symptoms and ask targeted clarifying questions (onset, severity 1-10, location, duration, aggravating/relieving factors).
2. Identify the most probable conditions and explain them clearly in plain language.
3. Triage urgency into one of three explicit tiers:
   - 🔴 EMERGENCY: Advise calling emergency services or going to an ER immediately.
   - 🟡 SEE A DOCTOR: Recommend scheduling an appointment within 24-72 hours.
   - 🟢 HOME CARE: Provide safe, general self-care guidance.
4. Always remind the user you are an AI and cannot replace a licensed physician.
5. Never name specific prescription drugs or dosages. You may reference general classes (e.g., "OTC antihistamines").
6. Use empathetic, calm, precise language. Avoid jargon without explanation.
7. If the user expresses distress or describes emergency symptoms (severe chest pain, stroke symptoms, difficulty breathing, suicidal ideation), lead with the emergency directive immediately.

Format responses with clear structure using markdown-style bold for key terms when helpful. Keep responses concise but complete."""

BUSY_NOTICE = (
    "⚠️ **Notice:** Our online AI engine is currently busy or unavailable. "
    "We are now switching to our built-in diagnostic engine to continue your assessment.\n\n"
)

@app.route("/")
def index():
    return send_from_directory(".", "index.html")

@app.route("/api/status")
def status():
    return jsonify({
        "ai_configured": bool(GEMINI_API_KEY),
        "ai_daily_limit": MAX_AI_REQUESTS_PER_DAY,
        "database": db.get_status_snapshot(),
    })

@app.route("/api/chat", methods=["POST"])
def chat():
    data = request.get_json(silent=True)
    if not data or not data.get("history"):
        return jsonify({"error": "Request body must include a 'history' array."}), 400

    front_history: list = data["history"]
    engine_preference = data.get("engine_preference", "auto")

    for msg in front_history:
        if not isinstance(msg, dict) or "role" not in msg or "content" not in msg:
            return jsonify({"error": "Each history item must have 'role' and 'content' fields."}), 400

    new_user_message = front_history[-1].get("content", "").strip()
    if not new_user_message:
        return jsonify({"error": "Last message content cannot be empty."}), 400

    prior_user_text = " ".join(
        m.get("content", "") for m in front_history[:-1] if m.get("role") == "user"
    )

    case_hash = db.hash_case(new_user_message)

    if engine_preference == "builtin":
        result = engine.build_report(new_user_message, history_text=prior_user_text)
        return jsonify({"text": result["report_text"], "engine": "engine", "tier": result["tier"]})

    if engine_preference == "gemini":
        ai_text, ai_error = _try_ai_engine(front_history, new_user_message)
        if ai_text:
            return jsonify({"text": ai_text, "engine": "ai", "tier": _guess_tier(ai_text)})
        else:
            # Send the exact crash message directly to the frontend chat bubble
            return jsonify({
                "text": f"**Gemini API Failed!**\n\n**Error:** `{ai_error}`\n\nPlease check your backend terminal for the full traceback.", 
                "engine": "error", 
                "tier": "unknown"
            })

    cached = db.get_cached_case(case_hash)
    if cached:
        response_text, urgency_tier, source = cached
        logger.info("Served cached case (originally generated by '%s').", source)
        note = (
            "🗂️ *A matching case was found in our records, so this assessment is being "
            "retrieved instantly instead of being regenerated.*\n\n"
        )
        return jsonify({"text": note + response_text, "engine": "cache", "tier": urgency_tier})

    ai_calls_today = db.get_today_ai_count()
    quota_exceeded = ai_calls_today >= MAX_AI_REQUESTS_PER_DAY
    ai_offline = not GEMINI_API_KEY

    if not ai_offline and not quota_exceeded:
        ai_text, ai_error = _try_ai_engine(front_history, new_user_message)
        if ai_text:
            db.save_case(case_hash, new_user_message, ai_text, _guess_tier(ai_text), source="ai")
            return jsonify({"text": ai_text, "engine": "ai", "tier": _guess_tier(ai_text)})
        logger.warning("Online AI engine failed, falling back to built-in engine: %s", ai_error)
    else:
        reason = "the daily usage limit has been reached" if quota_exceeded else "it has not been configured"
        logger.info("Skipping online AI engine because %s.", reason)

    result = engine.build_report(new_user_message, history_text=prior_user_text)
    report_text = result["report_text"]
    tier = result["tier"]

    final_text = report_text if result["is_clarifying"] else (BUSY_NOTICE + report_text)

    if not result["is_clarifying"]:
        db.save_case(case_hash, new_user_message, final_text, tier, source="engine")

    return jsonify({"text": final_text, "engine": "engine", "tier": tier})

def _guess_tier(text: str) -> str:
    if "🔴" in text:
        return "red"
    if "🟡" in text:
        return "yellow"
    if "🟢" in text:
        return "green"
    return "unknown"

def _try_ai_engine(front_history, new_user_message):
    try:
        from google import genai
        from google.genai import types

        gemini_history = []
        for msg in front_history[:-1]:
            if msg["role"] in ("system", "error"):
                continue
            role = "model" if msg["role"] == "assistant" else "user"
            gemini_history.append(
                types.Content(role=role, parts=[types.Part.from_text(text=msg["content"])])
            )

        client = genai.Client(api_key=GEMINI_API_KEY)
        config = types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            max_output_tokens=1024,
            temperature=0.4,
        )
        
        chat_kwargs = {
            "model": "gemini-3.1-flash-lite",
            "config": config
        }
        
        # Prevent crash if history is empty
        if gemini_history:
            chat_kwargs["history"] = gemini_history

        chat_session = client.chats.create(**chat_kwargs)
        response = chat_session.send_message(new_user_message)
        
        if not response or not getattr(response, "text", None):
            return None, "Empty response from AI. Safety filters might have blocked it."
            
        logger.info("Online AI engine responded successfully.")
        return response.text, None

    except Exception as exc:
        error_details = traceback.format_exc()
        logger.error(f"Gemini API Error:\n{error_details}")
        return None, str(exc)

@app.errorhandler(404)
def not_found(_):
    return jsonify({"error": "Endpoint not found."}), 404

@app.errorhandler(405)
def method_not_allowed(_):
    return jsonify({"error": "Method not allowed."}), 405

@app.errorhandler(500)
def server_error(_):
    return jsonify({"error": "An unexpected error occurred. Please try again."}), 500

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    debug = os.environ.get("FLASK_ENV") != "production"
    app.run(host="0.0.0.0", port=port, debug=debug)
